config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks, :invitations], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'notifications' => 'settings#notifications', as: :notifications
    put 'update_notifications' => 'settings#update_notifications', as: :update_notifications

    # Onboarding Routes
    get '/onboarding/index' => 'onboarding#index', as: :onboarding
    patch '/onboarding/update_user' => 'onboarding#update_user', as: :onboard_user
    patch '/onboarding/update_settings' => 'onboarding#update_settings', as: :onboard_settings
    get '/onboarding/complete' => 'onboarding#complete', as: :complete_onboard

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    resources :categories do
      resources :docs, except: [:index, :show]
    end
    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    resources :api_keys, except: [:show, :edit, :update]
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/team' => 'dashboard#stats', as: :stats
    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/entity/topic.rb
module Entity
  class Topic < Base
    expose :id, documentation: { type: "Integer" }
    expose :forum_id, documentation: { type: "Integer", desc: "The Forum this topic belongs to." }
    expose :user_id, documentation: { type: "Integer", desc: "The ID representing the creator of the topic."  }
    expose :user_name
    expose :name, documentation: { type: "String", desc: "The title or subject of the Topic thread." }
    expose :posts_count, documentation: { type: "Integer" }
    # expose :waiting_on, documentation: { type: "String", desc: "Maintained by system, currently unused" }
    expose :last_post_date
    expose :closed_date
    expose :last_post_id, documentation: { type: "Integer", desc: "Cached ID of the most recent post." }
    expose :current_status, documentation: { type: "String", desc: "The status of the Topic. Can be 'new', 'open', 'pending', 'closed', 'spam', 'trash'" }
    expose :private, documentation: { type: "String", desc: "Whether or not the Topic is private (a ticket). Tickets must also have forum_ID 1" }
    expose :assigned_user_id, documentation: { type: "Integer" }
    expose :points, documentation: { type: "Integer", desc: "The number of times this Topic has been voted for." }
    expose :created_at
    expose :updated_at
    expose :doc_id, documentation: { type: "Integer" }
    expose :locale, documentation: { type: "String", desc: "The locale used when the author created the Topic." }
    expose :team_list
    expose :posts, using: Entity::Post, if: { posts: true }
  end
end

app/controllers/topics_controller.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#  doc_id           :integer          default(0)
#

class TopicsController < ApplicationController

  before_action :authenticate_user!, :only => ['tickets','ticket']
  before_action :allow_iframe_requests
  before_action :forums_enabled?, only: ['index','show']
  before_action :topic_creation_enabled?, only: ['new', 'create']
  before_action :get_all_teams, only: 'new'
  before_action :get_public_forums, only: ['new', 'create']

  layout "clean", only: [:new, :index, :thanks]
  theme :theme_chosen

  # TODO Still need to so a lot of refactoring here!

  def index
    @forum = Forum.ispublic.where(id: params[:forum_id]).first
    if @forum
      if @forum.allow_topic_voting == true
        @topics = @forum.topics.ispublic.by_popularity.page params[:page]
      else
        @topics = @forum.topics.ispublic.chronologic.page params[:page]
      end
      @page_title = @forum.name
      add_breadcrumb t(:community, default: "Community"), forums_path
      add_breadcrumb @forum.name
    end
    respond_to do |format|
      format.html {
        redirect_to root_path unless @forum
      }
    end
  end

  def tickets
    @topics = current_user.topics.isprivate.undeleted.chronologic.page params[:page]
    @page_title = t(:tickets, default: 'Tickets')
    add_breadcrumb @page_title
    respond_to do |format|
      format.html # index.rhtml
    end
  end

  def ticket
    @topic = current_user.topics.undeleted.where(id: params[:id]).first
    if @topic
      @posts = @topic.posts.ispublic.chronologic.active.all.includes(:topic, :user, :screenshot_files)
      @page_title = "##{@topic.id} #{@topic.name}"
      add_breadcrumb t(:tickets, default: 'Tickets'), tickets_path
      add_breadcrumb @page_title
    end
    respond_to do |format|
      format.html {
        redirect_to root_path unless @topic
      }
    end
  end

  def new
    @page_title = t(:get_help_button, default: "Open a ticket")
    @topic = Topic.new
    @user = @topic.build_user unless user_signed_in?
    @topic.posts.build
    add_breadcrumb @page_title
  end

  def create
    params[:id].nil? ? @forum = Forum.find(params[:topic][:forum_id]) : @forum = Forum.find(params[:id])

    @topic = @forum.topics.new(
      name: params[:topic][:name],
      private: params[:topic][:private],
      doc_id: params[:topic][:doc_id],
      team_list: params[:topic][:team_list])#,
      #channel: 'web')

    if recaptcha_enabled?
      render :new && return unless verify_recaptcha(model: @topic)
    end

    if @topic.create_topic_with_user(params, current_user)
      @user = @topic.user
      @post = @topic.posts.create(
        :body => params[:topic][:posts_attributes]["0"][:body],
        :user_id => @user.id,
        :kind => 'first',
        :screenshots => params[:topic][:screenshots],
        :attachments => params[:topic][:posts_attributes]["0"][:attachments])

      if !user_signed_in?
        UserMailer.new_user(@user.id, @user.reset_password_token).deliver_later
      end

      # track event in GA
      tracker('Request', 'Post', 'New Topic')
      tracker('Agent: Unassigned', 'New', @topic.to_param)

      if @topic.private?
        redirect_to topic_thanks_path
      else
        redirect_to topic_posts_path(@topic)
      end
    else
      render 'new'
    end
  end

  def thanks
     @page_title = t(:thank_you, default: 'Thank You!')
  end

  def up_vote
    if user_signed_in?
      @topic = Topic.find(params[:id])
      @forum = @topic.forum
      @topic.votes.create(user_id: current_user.id)
      @topic.touch
      @topic.reload
    end
    respond_to do |format|
      format.js
    end
  end

  def tag
    @topics = Topic.ispublic.tag_counts_on(:tags)
  end

  private

  def post_params
    params.require(:post).permit(
      :body,
      :kind,
      {attachments: []}
    )
  end

  def post_params
    params.require(:post).permit(
      :body,
      :kind,
      {attachments: []}
    )
  end

  def get_public_forums
    @forums = Forum.ispublic.all
  end

end

app/controllers/widget/topics_controller.rb
class Widget::TopicsController < Widget::BaseController

  layout 'widget'
  before_action :allow_iframe_requests

  def new
    @page_title = t(:start_discussion, default: "Start a New Discussion")
    @locale = http_accept_language.compatible_language_from(I18n.available_locales)
    @forums = Forum.ispublic.all
    @topic = Topic.new
    @user = @topic.build_user unless user_signed_in?
    @topic.posts.build
    add_breadcrumb @page_title
  end


  def create

    @forum = Forum.find(1)
    @topic = @forum.topics.new(
      name: params[:topic][:name],
      private: params[:topic][:private],
      doc_id: params[:topic][:doc_id],
      team_list: params[:topic][:team_list])#,
      # channel: 'widget')

    @topic.private = true

    if @topic.create_topic_with_user(params, current_user)
      @user = @topic.user
      @post = @topic.posts.create(
        :body => params[:topic][:posts_attributes]['0'][:body],
        :user_id => @user.id,
        :kind => 'first'
        )

      if !user_signed_in?
        UserMailer.new_user(@user.id, @user.reset_password_token).deliver_later
      end

      # track event in GA
      tracker('Request', 'Post', 'New Topic')
      tracker('Agent: Unassigned', 'New', @topic.to_param)

      redirect_to widget_thanks_path
    else
      render 'new'
    end

  end

  def thanks
     @page_title = t(:thank_you, default: 'Thank You!')
  end


end

app/helpers/topics_helper.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#  doc_id           :integer          default(0)
#

module TopicsHelper

  def badge_for_status(status)
    content_tag(:span, status_label(status), class: "hidden-xs pull-right status-label label #{status_class(status)}")
  end

  def badge_for_private
    content_tag(:span, t(:private, default: 'PRIVATE'), class: 'hidden-xs pull-right status-label label label-private')
  end

  def control_for_status(status)
    content_tag(:span, "#{status_label(status)} <span class='caret'></span> ".html_safe, class: "change-status btn status-label-button label #{status_class(status)}")
  end

  def control_for_privacy(private_flag)
    str = private_flag ? t(:private, default: 'PRIVATE') : t(:public, default: 'PUBLIC')
    content_tag(:span, "#{str} <span class='caret'></span> ".html_safe, class: 'btn status-label-button change-privacy privacy-label label label-info')
  end

  def status_label(status)
    case status
      when 'new'
        t(:new, default: 'new')
      when 'open'
        t(:open, default: 'open')
      when 'active'
        t(:active, default: 'active')
      when 'assigned'
        t(:mine, default: 'mine')
      when 'closed'
        t(:closed, default: 'resolved')
      when 'pending'
        t(:pending, default: 'pending')
      when 'spam'
        t(:spam, default: 'spam')
      when 'trash'
        t(:trash, default: 'trash')
    end
  end

  def status_class(status)
    case status
      when 'new'
        'label-info'
      when 'open'
        'label-success'
      when 'closed'
        'label-default'
      when 'pending'
        'label-warning'
      when 'spam'
        'label-danger'
      when 'trash'
        'label-danger'
    end
  end


end

app/views/topics/_grid.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

  <div class="idea-box col-lg-3 col-md-3 col-sm-4 col-xs-12" data-link="<%= topic_posts_path(grid) %>" id="topic_<%= grid.id %>" >
    <div class="dummy"></div>
    <div class="thumbnail">
      <span class="more-important truncate-ellipsis text-left">
        <%= link_to h(grid.name), topic_posts_path(grid) %>
      </span>
      <div class="text-left">
         <%= grid.posts_count %> comments
      </div>
      <% if grid.forum.allow_post_voting == true %>
      <div id="post-vote-<%= grid.posts.first.id %>" class="grid-vote text-right">
        <%= link_to t(:upvote, count: grid.points), up_vote_path(grid.id), method: :post, remote: true, class: 'topic-vote', data: {voted: grid.to_param}, id: "upvote_#{grid.id}" %>
      </div>
      <% end %>
    </div>

  </div>

app/views/topics/_qna.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<% post = qna.posts.by_votes.first %>

  <div id="post-<%= post.id %>" class="media post-container kind-first<%= " inactive" unless post.active? %>">
    <div class="asked-question">
      <%= distance_of_time_in_words(Time.now,qna.created_at) %> ago <%= post_message(qna.posts.first) %>
    </div>
    <h4 class="qna"><%= link_to h(qna.name), topic_posts_path(qna) -%></h4>
    <div class="pull-left">
      <%= avatar_image(post.user, size=40) %>
  	</div>
  	<div class="media-body media-right">
  		<span class="hidden-sm hidden-md hidden-lg"><%= last_active_time(post.created_at) %><br/></span>
  		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
        <%= post_message(post) %>
  		</span>

  		<div id="post-body-<%= post.id %>" class="post-body less-important text-left">
  			<span class="shorten"><%= simple_format(post.body) -%></span>
        <% if post.topic.forum.allow_post_voting == true %>
  			<div id="post-vote-<%= post.id %>" class="btn btn-default">
  				<% if post.kind == 'first' %>
  				<%= link_to t(:upvote, count: post.topic.points), up_vote_path(post.topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: post.topic.to_param}, id: "upvote_#{post.topic.id}" %>
  				<% else %>
  				<%= link_to t(:upvote, count: post.points), post_vote_path(post.id), method: :post, remote: true, class: 'post-vote', data: {voted: post.topic.to_param}, id: "upvote_#{post.topic.id}" %>
  				<% end %>
  			</div>
  			<% end %>

  		</div>



  	</div>
  </div>

<hr/>

app/views/topics/_ticket.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<div class="ticket border-bottom row vcenter">
  <div class="col-md-8 text-left">
    <span class="truncate-ellipsis">
      <%= link_to "##{ticket.id}- #{ticket.name.capitalize}", ticket_path(ticket) -%>
    </span>
  </div>
  <div class="col-md-1">
    <%= badge_for_status(ticket.current_status) %>
  </div>
  <div class="col-md-1">
    <div class="label label-count hidden-xs pull-left"><%= ticket.posts_count %></div>
  </div>
  <div class="last-active less-important col-md-2 text-right">

    <%= last_active_time(ticket.updated_at) %>
  </div>
</div>

app/views/topics/_topic.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<tr id="topic_<%= topic.id %>" class="topic link-row">
  <% if topic.forum.allow_topic_voting == true %>
    <td>

      <div class="voting-widget">
        <!--<span class="glyphicon glyphicon-plus-sign"></span>-->
        <div class="vote-icon glyphicon glyphicon-chevron-up"></div>
        <div class="topic-points"><%= link_to topic.points, up_vote_path(topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: topic.to_param}, id: "upvote_#{topic.id}" %></div>
      </div>
    </td>
  <% end %>
  <td>
    <span class="more-important truncate-ellipsis"><%= link_to h(topic.name), topic_posts_path(topic) -%></span>
    <span class="less-important"><%= t(:started_by, :username => topic.user.name.titleize) %></span>
  </td>
  <td>
    <span class="label label-count hidden-xs"><%= topic.posts_count %></span>
  </td>
  <td class="last-active less-important text-right">
    <%= last_active_time(topic.last_post_date) %>
  </td>
</tr>

app/views/topics/index.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<%- title "#{AppSettings['settings.site_name']}: #{@page_title}" %>

<% if @forum.layout == "table" %>

<table id="forums" class="table-hover">

  <% if @forum.allow_topic_voting == true %>
  <col width="5%">
  <% end %>
  <col>
  <col width="5%">
  <col width="10%">

  <tbody>
    <tr>
      <% if @forum.allow_topic_voting == true %>
      <th colspan="3">
      <% else %>

      <th colspan="2">
      <% end %>
        <%= t(:topic) %></th>
  	  <th class="text-right"><%= t(:last_activity) %></th>
    </tr>
    <%= render :partial => 'topic', :collection => @topics %>
  </tbody>
</table>

<% elsif @forum.layout == "grid" %>
<div id="featured-categories" class="row">
  <%= render :partial => 'grid', :collection => @topics %>
</div>

<% elsif @forum.layout == "qna" %>
<div class="row">
	<div class="col-md-12">
    <div id="qnas">
      <%= render :partial => 'qna', :collection => @topics %>
    </div>
  </div>
</div>
<% end %>



<div class="text-right">
	<%= paginate @topics %>
</div>

<div>
  <% if user_signed_in? %>
    <span class="hidden-xs pull-right"><%= link_to t(:start_discussion, default: "Start Discussion"), new_topic_path, class: 'btn btn-primary' %></span>
  <% else %>
    <span class="hidden-xs pull-right"><%= link_to t(:start_discussion, default: "Start Discussion"), '#', data: {toggle: "modal", target: "#login-modal"}, class: 'btn btn-primary' %></span>
  <% end %>
</div>

app/views/topics/new.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<%- title "#{AppSettings['settings.site_name']}: #{@page_title}" %>

<div class="add-form row">
<%= simple_form_for(@topic, validate: true) do |f| -%>
  <div class="col-md-12">
    <%= render 'shared/error_messages', object: f.object %>

    <% unless user_signed_in? %>
      <%= f.simple_fields_for @user do |u| %>

        <%= u.input :email, placeholder: I18n.t('activerecord.attributes.user.email'), autofocus: true, class: 'topic-placeholder' %>
        <%= u.input :name, placeholder: I18n.t('activerecord.attributes.user.name'), class: 'topic-placeholder' %>

      <% end %>
    <% end %>

    <% if (user_signed_in? && !@widget) || (!user_signed_in? && recaptcha_enabled? && !@widget) %>
      <% if forums? and tickets? %>
        <label class="control-label" for="doc_active"> <%= t(:should_message_be_private) %> </label>
        <%= f.collection_radio_buttons :private, [[true, t(:only_support_can_respond)] ,[false, t(:responses_can_come_from_everyone)]], :first, :last, item_wrapper_class: 'radio', item_label_class: 'radio-label', collection_wrapper_tag: :div %>
        <%= f.input(:forum_id, collection: @forums, :label => t(:forum_name), locale: I18n.locale, prompt: nil) %>
      <% elsif forums? && !tickets? %>
        <%= f.input(:forum_id, collection: @forums, :label => t(:forum_name), locale: I18n.locale, prompt: nil) %>
        <%= f.hidden_field :private, value: false %>
      <% elsif tickets? && !forums? %>
        <%= f.hidden_field :private, value: true %>
        <%= f.hidden_field :forum_id, value: 1 %>
      <% end %>
    <% else %>
      <%= f.hidden_field :private, value: true %>
      <%= f.hidden_field :forum_id, value: 1 %>
    <% end %>
    <% if teams? and tickets? and !@widget %>
    <script>
      $(document).ready(function(){
        Helpy.showGroup();
      });
    </script>
    <% end %>

    <%= f.input(:team_list, collection: @all_teams, :label => t(:assign_to), locale: I18n.locale, prompt: "", style: "display:none;") if teams? and !@widget and @all_teams.count > 0 %>
    <%= f.input :name, input_html: { value: params[:q], class: 'suggest-results' }, :size => 40,  placeholder: I18n.t(:subject), label: I18n.t(:subject), class: 'disable-empty topic-placeholder' %>

    <div class="suggestion-results-container hidden">
      <strong><%= t(:asked_before, default: 'Has your question been answered before? We think these may be similar') %>:</strong>
      <br/><br/>
      <div class="suggestion-results">
      </div>
    </div>

    <%= f.simple_fields_for :posts do |p| %>
      <%= p.input :body, input_html: {:rows => 8, :cols => 60, placeholder: I18n.t(:how_can_we_help), label: 'Message', class: 'disable-empty form-control topic-placeholder'} %>
      <% unless cloudinary_enabled? %>
        <%= p.file_field :attachments, multiple: true %>
        <ul class="list-inline" id="attachments">
          <%#= render partial: 'posts/attachment', locals: { :model_name => @post } %>
        </ul>
      <% end %>
    <% end %>

    <div class="add-screenshots">
      <% if !@widget %>
      <%= attachinary_file_field_tag 'topic[screenshots]', @topic, :screenshots if cloudinary_enabled? %>
      <% end %>
    </div>



    <% if !user_signed_in? && recaptcha_enabled? && !@widget %>
      <div class="form-group">
        <%= recaptcha_tags %>
      </div>
    <% end %>

    <%= hidden_field_tag :client_id %>
    <%= f.hidden_field :doc_id, value: params[:doc_id] if params[:doc_id] %>
    <%= hidden_field_tag :from, 'widget' if params[:controller] == 'widget' || params[:from] == 'widget' %>

    <!--<label>Tags:</label><br/>-->
    <%#= text_field_tag :tags %>

    <%= f.submit t(:submit_start_discussion, default: 'Start Discussion'), class: 'btn btn-warning disableable', disabled: 'disabled' %>
  </div>
<% end -%>

</div>

app/views/topics/tag.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<div id="breadcrumbs">
  <%= link_to 'Forums', forums_path -%> > <strong>Tagged with <%= h params[:id] -%></strong>
</div>

<div class="Paginator" align="right">
	<%#= will_paginate @topics %>
</div>

<table id="topics">

  <col width="55%">
  <col width="5%">
  <col width="10%">
  <col width="5%">
  <col width="20%">

  <tr>
    <th colspan="2">Topic</th>
    <th>Status</th>
    <th>Replies</th>
	<th>Last Post</th>
  </tr>
  <%= render :partial => 'topic', :collection => @topics %>
</table>

<div class="Paginator" align="right">
	<%#= will_paginate @topics %>
</div>