config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks, :invitations], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'notifications' => 'settings#notifications', as: :notifications
    put 'update_notifications' => 'settings#update_notifications', as: :update_notifications

    # Onboarding Routes
    get '/onboarding/index' => 'onboarding#index', as: :onboarding
    patch '/onboarding/update_user' => 'onboarding#update_user', as: :onboard_user
    patch '/onboarding/update_settings' => 'onboarding#update_settings', as: :onboard_settings
    get '/onboarding/complete' => 'onboarding#complete', as: :complete_onboard

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    resources :categories do
      resources :docs, except: [:index, :show]
    end
    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    resources :api_keys, except: [:show, :edit, :update]
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/team' => 'dashboard#stats', as: :stats
    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  login                  :string
#  identity_url           :string
#  name                   :string
#  admin                  :boolean          default(FALSE)
#  bio                    :text
#  signature              :text
#  role                   :string           default("user")
#  home_phone             :string
#  work_phone             :string
#  cell_phone             :string
#  company                :string
#  street                 :string
#  city                   :string
#  state                  :string
#  zip                    :string
#  title                  :string
#  twitter                :string
#  linkedin               :string
#  thumbnail              :string
#  medium_image           :string
#  large_image            :string
#  language               :string           default("en")
#  assigned_ticket_count  :integer          default(0)
#  topics_count           :integer          default(0)
#  active                 :boolean          default(TRUE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  provider               :string
#  uid                    :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#  invitations_count      :integer          default(0)
#  invitation_message     :text
#  time_zone              :string           default("UTC")
#  profile_image          :string
#  notify_on_private      :boolean          default(FALSE)
#  notify_on_public       :boolean          default(FALSE)
#  notify_on_reply        :boolean          default(FALSE)
#  account_number         :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => Devise.omniauth_providers

  INVALID_NAME_CHARACTERS = /\A('|")|('|")\z/

  # Add preferences to user model
  include RailsSettings::Extend

  TEMP_EMAIL_PREFIX = 'change@me'

  attr_accessor :opt_in

  validates :name, presence: true, format: { with: /\A\D+\z/ }
  validates :email, presence: true


  include Gravtastic
  mount_uploader :profile_image, ProfileImageUploader

  include PgSearch
  pg_search_scope :user_search,
                  against: [:name, :login, :email, :company, :account_number, :home_phone, :work_phone, :cell_phone]

  paginates_per 15

  # Relationships
  has_and_belongs_to_many :roles
  has_many :topics
  has_many :posts
  has_many :votes
  has_many :docs
  has_many :api_keys
  has_attachment  :avatar, accept: [:jpg, :png, :gif]
  is_gravtastic

  after_invitation_accepted :set_role_on_invitation_accept
  after_create :enable_notifications_for_admin
  before_save :reject_invalid_characters_from_name
  acts_as_taggable_on :teams

  ROLES = %w[admin agent editor user]

  # TODO: Will want to refactor this using .or when upgrading to Rails 5
  scope :admins, -> { where('admin = ? OR role = ?',true,'admin').order('name asc') }
  scope :agents, -> { where('admin = ? OR role = ? OR role = ?',true,'admin','agent').order('name asc') }
  scope :active, -> { where('active = ?', true)}

  def set_role_on_invitation_accept
    if self.role.nil?
      self.role = "agent"
    end
    self.active = true
    self.save
  end

  def enable_notifications_for_admin
    if self.role == "admin"
      self.notify_on_private = true
      self.notify_on_public = true
      self.notify_on_reply = true
    end
  end

  def self.notifiable_on_public
    User.agents.where(notify_on_public: true).reorder('id asc')
  end

  def self.notifiable_on_private
    User.agents.where(notify_on_private: true).reorder('id asc')
  end

  def self.notifiable_on_reply
    User.agents.where(notify_on_reply: true).reorder('id asc')
  end

  def active_assigned_count
    Topic.where(assigned_user_id: self.id).active.count
  end

  def is_restricted?
    self.team_list.count > 0 && !self.is_admin?
  end

  def self.create_password
    Devise.friendly_token
  end

  def thumbnail_url
    self.thumbnail.blank? ? self.gravatar_url(size: 60) : self.thumbnail
  end

  def image_url
    self.medium_image || self.gravatar_url(size: 60)
  end

  def self.find_for_oauth(auth)
    user = find_by(email: auth.info.email)
    if user
      user.tap do |u|
        u.provider = auth.provider
        u.uid = auth.uid
        u.save!
      end
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |u|
        u.provider = auth.provider
        u.uid = auth.uid
        u.email = auth.info.email.present? ? auth.info.email : u.temp_email(auth)
        u.name = auth.info.name
        u.thumbnail = auth.info.image
        u.password = Devise.friendly_token[0,20]
      end
    end
  end

  def temp_email(auth)
    "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com"
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def signup_guest
    enc = Devise.token_generator.generate(User, :reset_password_token)
    self.reset_password_token = enc
    self.reset_password_sent_at = Time.now.utc

    self.login = self.email.split("@")[0]
    self.password = User.create_password
    self.save
  end


  # NOTE: Could have user AR Enumerables for this, but the field was already in the database as a string
  # and changing it could be painful for upgrading installed users. These are three
  # Utility methods for checking the role of an admin:

  def is_admin?
    self.role == 'admin'
  end

  def is_agent?
    %w( agent admin ).include?(self.role)
  end

  def is_editor?
    %w( editor agent admin ).include?(self.role)
  end

  def self.bulk_invite(emails, message, role)
    #below line merge comma saperated emails as well as emails saperated by new lines
    emails = emails.each_line.reject { |l| l =~ /^\s+$/ }.map { |l| l.strip.split(', ') }.flatten

    emails.each do |email|
      is_valid_email = email.match('^.+@.+$')
      if is_valid_email
        User.invite!({email: email}) do |user|
          user.invitation_message = message
          user.name = "Invited User: #{email}"
          user.role = role
          user.active = false
        end
      end
    end
  end

  #when using deliver_later attr_accessor :message becomes nil on mailer view
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  private

  def reject_invalid_characters_from_name
    self.name = name.gsub(INVALID_NAME_CHARACTERS, '') if !!name.match(INVALID_NAME_CHARACTERS)
  end

end

app/controllers/widget/topics_controller.rb
class Widget::TopicsController < Widget::BaseController

  layout 'widget'
  before_action :allow_iframe_requests

  def new
    @page_title = t(:start_discussion, default: "Start a New Discussion")
    @locale = http_accept_language.compatible_language_from(I18n.available_locales)
    @forums = Forum.ispublic.all
    @topic = Topic.new
    @user = @topic.build_user unless user_signed_in?
    @topic.posts.build
    add_breadcrumb @page_title
  end


  def create

    @forum = Forum.find(1)
    @topic = @forum.topics.new(
      name: params[:topic][:name],
      private: params[:topic][:private],
      doc_id: params[:topic][:doc_id],
      team_list: params[:topic][:team_list])#,
      # channel: 'widget')

    @topic.private = true

    if @topic.create_topic_with_user(params, current_user)
      @user = @topic.user
      @post = @topic.posts.create(
        :body => params[:topic][:posts_attributes]['0'][:body],
        :user_id => @user.id,
        :kind => 'first'
        )

      if !user_signed_in?
        UserMailer.new_user(@user.id, @user.reset_password_token).deliver_later
      end

      # track event in GA
      tracker('Request', 'Post', 'New Topic')
      tracker('Agent: Unassigned', 'New', @topic.to_param)

      redirect_to widget_thanks_path
    else
      render 'new'
    end

  end

  def thanks
     @page_title = t(:thank_you, default: 'Thank You!')
  end


end

app/helpers/topics_helper.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#  doc_id           :integer          default(0)
#

module TopicsHelper

  def badge_for_status(status)
    content_tag(:span, status_label(status), class: "hidden-xs pull-right status-label label #{status_class(status)}")
  end

  def badge_for_private
    content_tag(:span, t(:private, default: 'PRIVATE'), class: 'hidden-xs pull-right status-label label label-private')
  end

  def control_for_status(status)
    content_tag(:span, "#{status_label(status)} <span class='caret'></span> ".html_safe, class: "change-status btn status-label-button label #{status_class(status)}")
  end

  def control_for_privacy(private_flag)
    str = private_flag ? t(:private, default: 'PRIVATE') : t(:public, default: 'PUBLIC')
    content_tag(:span, "#{str} <span class='caret'></span> ".html_safe, class: 'btn status-label-button change-privacy privacy-label label label-info')
  end

  def status_label(status)
    case status
      when 'new'
        t(:new, default: 'new')
      when 'open'
        t(:open, default: 'open')
      when 'active'
        t(:active, default: 'active')
      when 'assigned'
        t(:mine, default: 'mine')
      when 'closed'
        t(:closed, default: 'resolved')
      when 'pending'
        t(:pending, default: 'pending')
      when 'spam'
        t(:spam, default: 'spam')
      when 'trash'
        t(:trash, default: 'trash')
    end
  end

  def status_class(status)
    case status
      when 'new'
        'label-info'
      when 'open'
        'label-success'
      when 'closed'
        'label-default'
      when 'pending'
        'label-warning'
      when 'spam'
        'label-danger'
      when 'trash'
        'label-danger'
    end
  end


end

app/views/admin/topics/_post.html.erb
<!-- Admin post partial -->
<div id="post-<%= post.id %>" class="media post-container disallow-post-voting <%= "kind-#{post.kind}" %><%= " inactive" unless post.active? %> overflow-visible">
	<div class="pull-left">
		<%= avatar_image(post.user, size=40) %>
	</div>
	<div class="media-body media-right overflow-visible">
		<span class="hidden-sm hidden-md hidden-lg"><%= last_active_time(post.created_at) %><br/></span>
		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
			<%= post_message(post,true) %>
			<ul class="dropdown-menu dropdown-menu-left" role="menu">
				<li><%= link_to t('edit', default: "Edit"), edit_admin_post_path(post), remote: true %></li>
				<li><%= link_to t('convert_content', default: 'Turn post into content'), new_admin_doc_path(post_id: post.id, lang: I18n.locale) %></li>
        <li><%= link_to t('new_discussion', default: 'Create new discussion from this'), admin_split_topic_path(topic_id: post.topic_id, post_id: post.id), method: :post, remote: true %></li>
        <li><%= link_to t('change_owner', default: 'Change author'), '#', data: { toggle: "modal", target: "#change-user-modal-#{post.id}" } %></li>
        <%= content_tag :li, link_to(t('Show Raw Email', default: 'Raw Email'), admin_post_raw_path(post), target: 'blank') if post.raw_email.present? %>
			</ul>
		</span>

		<span class="last-active posted-at less-important pull-right">
			<span class="hidden-xs">
			<%= last_active_time(post.created_at) %>
			</span>
		</span>
		<%= content_tag :div, post.cc.present? ? "cc: #{post.cc}" : "", class: 'post-cc post-cc-style' %>
		<%= content_tag :div, post.bcc.present? ? "bcc: #{post.bcc}" : "", class: 'post-bcc post-cc-style' %>
		<div id="post-body-<%= post.id %>" class="post-body less-important text-left">
			<%= simple_format(post.body) -%>
      <%= render partial: 'posts/thumbnail', locals: { :model_name => post } %>
			<%= render partial: 'posts/attachment', locals: { :model_name => post } %>
		</div>

	</div>

  <div id="change-user-modal-<%= post.id %>" class="modal fade change-user-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"><%= t('change_owner', default: 'Change author') %></h4>
        </div>

        <div class="modal-body row">
          <div class="col-md-12">
            <%= bootstrap_form_tag url: admin_user_search_path, method: 'post', remote: true, html: { class: 'search_form' } do |f| -%>
              <%= hidden_field_tag 'post_id', post.id %>
              <%= f.text_field :user_search, skip_label: true, placeholder: 'Type users name or email', autocomplete: :off, onkeyup: "search_user(#{post.id})" -%>
            <% end -%>
            <div class="search-results">
            </div>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>

app/views/admin/topics/_ticket.html.erb
<div id="ticket-info" class="no-side-pad row">

  <div class="col-md-4 hidden-xs hidden-sm" id="left-col-user-info">
    <%= render partial: 'admin/users/user_info' %>
  </div>

  <div id="ticket-controls" class="col-md-8 col-xs-12 col-lg-8">
    <h2>
      <%= render 'admin/topics/ticket_nav_dropdown' %> #<%= @topic.id %>- <%= best_in_place @topic, :name, url: admin_topic_path(@topic), :class => "edit-topic-name" -%>&nbsp;
    </h2>
    <div id="topic-options">
    <%= render :partial => 'admin/topics/topic_options' %>
    </div>
    <% if @posts  %>
      <script>
        Helpy.messages = '<%= j t(:collapsed_messages, count: @posts.count-2) %>';
      </script>
    <% end %>
    <div id="posts">
    <%= render :partial => 'admin/topics/post', :collection => @posts %>
    </div>

    <div class="add-form">
      <h4><%= t(:reply_to_this_topic, default: 'Reply to this Topic') %>:</h4>

      <%= bootstrap_form_for @topic.posts.new, url: admin_topic_posts_path(@topic), remote: true, multipart: true do |f| %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

        <%= f.form_group :kind  do %>
          <%= f.radio_button :kind, 'reply', label: t(:reply, default: "Reply"), checked: true, inline: true %>
          <%= f.radio_button :kind, 'note', label: t(:internal_note, default: "Internal Note"), inline: true %>
          <%= content_tag(:span, '', class: 'fa fa-angle-down pull-right cc-bcc-toggle', role: 'button') %>
        <% end %>
        <span class="cc-bcc hidden">
        <%= f.text_field :cc, hide_label: true, placeholder: 'cc:' %>
        <%= f.text_field :bcc, hide_label: true, placeholder: 'bcc:' %>
        </span>

        <%= hidden_field_tag :client_id %>
        <%= hidden_field_tag :from, 'admin' %>
        <%= f.text_area :body, :rows => 8, :cols => 160, hide_label: true, placeholder: t(:type_reply, default: "Type your reply, or select from a common message below"), class: 'disable-empty' %>

        <%= label_tag 'post_reply_id', "#{t(:select_common, default: 'Insert Common Reply')} (#{link_to(t(:edit, default: 'Edit'), admin_category_path(1), target: 'blank')})".html_safe, class: 'control-label' %>
        <%= f.select_tag 'post[reply_id]', grouped_options_for_select(i18n_reply_grouped_options, nil, prompt: ''), class: 'form-control', id: 'post_reply_id' %>
        <br/>
        <%= f.attachinary_file_field :screenshots if cloudinary_enabled? %>
        <%= f.file_field :attachments, multiple: true unless cloudinary_enabled? %>
        <%= f.submit t(:submit_reply), class: 'btn btn-warning disableable', disabled: true -%>
        <%= f.check_box :resolved, label: t(:mark_as_resolved, default: "Mark as resolved"), inline: true unless @topic.current_status == 'closed' %>
      <% end -%>

    </div>
  </div>


</div>

app/views/admin/topics/_topic_options.html.erb
<script>
  Helpy.topicID = <%= @topic.id %>;
</script>
<span class="btn-group left-col-dropdown">
  <button class="status dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
    <%= control_for_status(@topic.current_status) %>
  </button>
  <ul class="dropdown-menu ticket-controls" role="menu">
    <li><%= link_to t(:mark_closed, default: 'Mark Closed'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'closed'), :remote => true, class: 'key-sr' unless @topic.current_status == "closed" %></li>
    <li><%= link_to t(:reopen, default: 'Reopen'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'reopen'), :remote => true, class: 'key-so' unless @topic.current_status == "open" %></li>
    <li><%= link_to t(:mark_new, default: 'Mark New'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'new'), :remote => true, class: 'key-sn' unless @topic.current_status == "new" %></li>
    <li><%= link_to t(:mark_spam, default: 'Mark Spam'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'spam'), :remote => true, class: 'key-ss' unless @topic.current_status == "spam" %></li>
    <li><%= link_to t(:trash, default: 'Trash'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'trash'), :remote => true, class: 'key-st' unless @topic.current_status == "trash" %></li>
  </ul>
</span>

<% if forums? %>
  <span class="status privacy btn-group left-col-dropdown">
    <button class="privacy-toggle dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
      <%= control_for_privacy(@topic.private?) %>
    </button>
    <ul class="dropdown-menu ticket-controls" role="menu">
      <% Forum.where(private: false).alpha.each do |forum| %>
      <li><%= link_to "#{t(:move_to, default: "Move")}: #{forum.name}", admin_toggle_privacy_path(topic_ids: { "":@topic.id }, private: 'false', forum_id: forum.id), :remote => true %></li>
      <% end %>
      <li><%= link_to "#{t(:mark_as, default: "Mark")}: Private", admin_toggle_privacy_path(topic_ids: { "":@topic.id }, private: 'true', forum_id: 1), :remote => true %></li>
    </ul>
  </span>
<% end %>

<% unless @topic.current_status == "closed" %>
  <span class="status btn-group left-col-dropdown">
    <button class="dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
      <%= content_tag :span, class: 'btn status-label-button label label-warning assign-to' do %>
        <%= @topic.assigned_user.try(:name).try(:upcase) || t(:unassigned, default: 'UNASSIGNED') %>
        <%= icon('caret-down') + ' ' %>
      <% end %>
    </button>
    <ul class="dropdown-menu ticket-controls" role="menu">
      <% @admins.each do |admin| %>
      <li><%= link_to "#{admin.name.titleize} (#{admin.active_assigned_count})", admin_assign_agent_path(topic_ids: { "":@topic.id }, assigned_user_id: admin.id), :remote => true unless @topic.current_status == "closed" %></li>
      <% end %>
    </ul>
  </span>

  <% if teams? %>
    <span class="status btn-group left-col-dropdown">
      <button class="dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
        <%= content_tag(:span, class: "btn status-label-button group-to label label-#{@topic.team_list.present? ? @topic.team_list.first.first.downcase : 'default'}") do %>
          <%= @topic.team_list.first.try(:upcase) || t(:no_team_assigned, default: 'Assign to group') %>
          <%= icon('caret-down') + ' ' %>
        <% end %>
      </button>
      <ul class="dropdown-menu ticket-controls team-list" role="menu">
        <% @all_teams.to_a.each do |team| %>
          <li class='team-item'>
            <% unless @topic.current_status == "closed" %>
              <%= link_to("#{content_tag(:div, '', class: 'color-sample label-' + team.first.downcase)} #{content_tag :div, team.try(:titleize)}".html_safe, admin_assign_team_path(topic_ids: { "":@topic.id }, team: team), :remote => true) %>
            <% end %>
          </li>
        <% end %>
        <li class="new-tag">
          <%= form_tag '#', class: 'new-group-form' do %>
          <%= text_field_tag "new_group", '', placeholder: "Add a new group", class: 'form-control' %><%#= link_to "Add", '#', class: 'btn btn-default pull-right add-new-group' %>
          <% end %>
        </li>
        <li><%= link_to "Unassign from group", admin_assign_team_path(topic_ids: { "":@topic.id }, team: ''), :remote => true unless @topic.current_status == "closed" %></li>

      </ul>
    </span>
  <% end %>
<% end %>

app/views/admin/topics/update_ticket.js.erb
$('#tickets').html("<%= escape_javascript(render 'admin/topics/ticket') %>");
$('.ticket-stats').html("<%= j render 'admin/topics/ticket_stats' %>");
history.pushState(null, null, '<%= admin_topic_path @topic %>');

// Update timestamps
$('.last-active time[data-time-ago]').timeago();

// jQuery hook
Helpy.ready();
Helpy.track();

// RTL changes?
<%= "Helpy.rtl();" if rtl? %>