config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks, :invitations], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'notifications' => 'settings#notifications', as: :notifications
    put 'update_notifications' => 'settings#update_notifications', as: :update_notifications

    # Onboarding Routes
    get '/onboarding/index' => 'onboarding#index', as: :onboarding
    patch '/onboarding/update_user' => 'onboarding#update_user', as: :onboard_user
    patch '/onboarding/update_settings' => 'onboarding#update_settings', as: :onboard_settings
    get '/onboarding/complete' => 'onboarding#complete', as: :complete_onboard

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    resources :categories do
      resources :docs, except: [:index, :show]
    end
    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    resources :api_keys, except: [:show, :edit, :update]
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/team' => 'dashboard#stats', as: :stats
    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/doc.rb
# == Schema Information
#
# Table name: docs
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  keywords         :string
#  title_tag        :string
#  meta_description :string
#  category_id      :integer
#  user_id          :integer
#  active           :boolean          default(TRUE)
#  rank             :integer
#  permalink        :string
#  version          :integer
#  front_page       :boolean          default(FALSE)
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  topics_count     :integer          default(0)
#  allow_comments   :boolean          default(TRUE)
#  attachments      :string           default([]), is an Array
#

class Doc < ActiveRecord::Base

  include SentenceCase

  belongs_to :category
  belongs_to :user
  has_many :votes, :as => :voteable
  has_one :topic
  has_many :posts, through: :topic

  validates :title, presence: true
  validates :body, presence: true
  validates :category_id, presence: true

  include PgSearch
  multisearchable :against => [:title, :body, :keywords], :if => :active
  has_paper_trail

  translates :title, :body, :keywords, :title_tag, :meta_description, fallbacks_for_empty_translations: false, versioning: :paper_trail
  globalize_accessors

  paginates_per 25
  has_attachments :screenshots, accept: [:jpg, :jpeg, :png, :gif, :pdf]

  include RankedModel
  ranks :rank

  acts_as_taggable
  acts_as_taggable_on :tags

  scope :alpha, -> { order('title ASC') }
  scope :by_category, -> { order(:category_id) }
  scope :in_category, -> (cat) { where(category_id: cat).order('front_page DESC, rank ASC') }
  scope :ordered, -> { order('rank ASC') }
  scope :active, -> { where(active: true) }
  scope :recent, -> { order('last_updated DESC').limit(5) }
  scope :all_public_popular, -> { where(active: true).order('points DESC').limit(6) }
  scope :replies, -> { where(category_id: 1) }

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def read_translated_attribute(name)
    globalize.stash.contains?(Globalize.locale, name) ? globalize.stash.read(Globalize.locale, name) : translation_for(Globalize.locale).send(name)
  end

  def content
    c = RDiscount.new(self.body)
    return c.to_html
  end

end

app/controllers/admin/docs_controller.rb
class Admin::DocsController < Admin::BaseController

  before_action :verify_editor
  respond_to :html, only: ['new','edit','create']
  respond_to :js, only: ['destroy']

  def new
    @doc = Doc.new
    @doc.category_id = params[:category_id]
    @doc.body = Post.where(id: params[:post_id]).first.body if params[:post_id]
    @categories = Category.alpha
  end

  def edit
    @doc = Doc.find(params[:id])
    @category = Category.where(id: params[:category_id]).first
    @categories = Category.alpha
  end

  def create
    @doc = Doc.new(doc_params)
    @doc.user_id = current_user.id
    if @doc.save
      redirect_to(admin_category_path(@doc.category.id))
    else
      render 'new'
    end
  end

  def update
    unless params['lang'].nil?
      I18n.locale = params['lang']
    end
    @doc = Doc.where(id: params[:id]).first
    @category = @doc.category
    # @doc.tag_list = params[:doc][:tag_list]
    if @doc.update_attributes(doc_params)
      respond_to do |format|
        format.html {
          redirect_to(admin_category_path(@category.id))
        }
        format.js {
        }
      end
    else
      respond_to do |format|
        format.html {
          render 'edit', id: @doc
        }
      end
    end

  end

  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy
    render js:"
      $('#doc-#{@doc.id}').fadeOut();
      Helpy.ready();
      Helpy.track();"
  end

  private

  def doc_params
    params.require(:doc).permit(
    :title,
    :body,
    :keywords,
    :title_tag,
    :meta_description,
    :category_id,
    :rank,
    :active,
    :front_page,
    :allow_comments,
    {screenshots: []},
    :tag_list
  )
  end

end

app/controllers/api/v1/docs.rb
module API
  module V1
    class Docs < Grape::API

      before do
        authenticate!
        restrict_to_role %w(admin agent)
      end

      include API::V1::Defaults
      resource :docs, desc: "Manage knowledgebase documents" do

        # throttle max: 200, per: 1.minute

        # SHOW A SINGLE DOC
        desc "Shows a single doc", {
          entity: Entity::Doc,
          notes: "Returns the full content of one doc"
        }
        params do
          requires :id, type: String, desc: "ID of the doc to show"
          optional :category, type: Boolean, desc: "Whether to return the category object in full"
        end
        get ":id", root: "doc" do
          doc = Doc.active.find(permitted_params[:id])
          present doc, with: Entity::Doc, category: permitted_params[:category]
        end

        # CREATE NEW DOC
        desc "Create a new doc", {
          entity: Entity::Doc,
          notes: "Create a new doc"
        }
        params do
          requires :title, type: String, desc: "The name of the articles"
          requires :category_id, type: Integer, desc: "The category the doc belongs to"
          requires :body, type: String, desc: "The body/text of the article"
          requires :user_id, type: Integer, desc: "The author of the article"
          optional :keywords, type: String, desc: "Keywords that will be used for internal search and SEO"
          optional :title_tag, type: String, desc: "An alternate title tag that will be used if provided"
          optional :meta_description, type: String, desc: "A short description for SEO and internal purposes"
          optional :rank, type: Integer, desc: "The rank can be used to determine the ordering of docs"
          optional :front_page, type: Boolean, desc: "Whether or not the doc should appear on the front page"
          optional :active, type: Boolean, desc: "Whether or not the doc is live on the site"
        end
        post "", root: :docs do
          doc = Doc.create!(
            title: permitted_params[:title],
            category_id: permitted_params[:category_id],
            body: permitted_params[:body],
            user_id: permitted_params[:user_id],
            keywords: permitted_params[:keywords],
            title_tag: permitted_params[:title_tag],
            meta_description: permitted_params[:meta_description],
            rank: permitted_params[:rank],
            front_page: permitted_params[:front_page],
            active: permitted_params[:active]
          )
          present doc, with: Entity::Doc
        end

        # UPDATE EXISTING DOC
        desc "Update a doc", {
          entity: Entity::Doc,
          notes: "Update a doc"
        }
        params do
          requires :id, type: Integer, desc: "The ID of the Doc being updated"
          optional :title, type: String, desc: "The name of the category of articles"
          optional :category_id, type: Integer, desc: "The category the doc belongs to"
          optional :body, type: String, desc: "The body/text of the article"
          optional :user_id, type: Integer, desc: "The author of the article"
          optional :keywords, type: String, desc: "Keywords that will be used for internal search and SEO"
          optional :title_tag, type: String, desc: "An alternate title tag that will be used if provided"
          optional :meta_description, type: String, desc: "A short description for SEO and internal purposes"
          optional :rank, type: Integer, desc: "The rank can be used to determine the ordering of docs"
          optional :front_page, type: Boolean, desc: "Whether or not the doc should appear on the front page"
          optional :active, type: Boolean, desc: "Whether or not the doc is live on the site"
        end
        patch ":id", root: :docs do
          doc = Doc.find(permitted_params[:id])
          doc.update!(
            title: permitted_params[:title],
            category_id: permitted_params[:category_id],
            body: permitted_params[:body],
            user_id: permitted_params[:user_id],
            keywords: permitted_params[:keywords],
            title_tag: permitted_params[:title_tag],
            meta_description: permitted_params[:meta_description],
            rank: permitted_params[:rank],
            front_page: permitted_params[:front_page],
            active: permitted_params[:active]
          )
          present doc, with: Entity::Doc
        end

      end
    end
  end
end

app/controllers/docs_controller.rb
# == Schema Information
#
# Table name: docs
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  keywords         :string
#  title_tag        :string
#  meta_description :string
#  category_id      :integer
#  user_id          :integer
#  active           :boolean          default(TRUE)
#  rank             :integer
#  permalink        :string
#  version          :integer
#  front_page       :boolean          default(FALSE)
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  topics_count     :integer          default(0)
#  allow_comments   :boolean          default(TRUE)
#  attachments      :string           default([]), is an Array
#

class DocsController < ApplicationController

  before_action :knowledgebase_enabled?, only: ['show']
  theme :theme_chosen

  respond_to :html

  def show
    @doc = Doc.where(id: params[:id]).active.first

    unless @doc.nil?
      @page_title = @doc.title
      @custom_title = @doc.title_tag.blank? ? @page_title : @doc.title_tag
      @topic = @doc.topic.present? ? @doc.topic : Topic.new
      @post = @doc.topic.present? ? @topic.posts.new : Post.new
      @posts = @topic.posts.ispublic.active.includes(:user) unless @topic.nil?
      @forum = Forum.for_docs.first
      @comment = @forum.topics.new
      @user = User.new unless user_signed_in?
      add_breadcrumb t(:knowledgebase, default: "Knowledgebase"), categories_path
      add_breadcrumb @doc.category.name, category_path(@doc.category) if @doc.category.name
      add_breadcrumb @doc.title
    else
      redirect_to root_url
    end
  end

end

app/helpers/docs_helper.rb
# == Schema Information
#
# Table name: docs
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  keywords         :string
#  title_tag        :string
#  meta_description :string
#  category_id      :integer
#  user_id          :integer
#  active           :boolean          default(TRUE)
#  rank             :integer
#  permalink        :string
#  version          :integer
#  front_page       :boolean          default(FALSE)
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  topics_count     :integer          default(0)
#  allow_comments   :boolean          default(TRUE)
#  attachments      :string           default([]), is an Array
#

module DocsHelper
end

app/views/admin/docs/_attachment.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<% doc.attachments.each do |att| %>
  <%= content_tag(:li, class: "#{att.file.extension}") do %>
    <% if %w(png jpg jpeg gif).include?(att.file.extension) %>
      <%= link_to image_tag(att, style: "width: 125px; height: 125px"), att.url, class: 'screenshot-link', target: 'blank' %>
    <% else %>
      <%= link_to att.url, title: att.url, target: 'blank' do %>
        <%= content_tag(:i, '', class: attachment_icon(att.url)) %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/docs/_form.html.erb
  <style>
  /* Added style to handle new h1 header in trix.js */
  .simple_form h1 {
    font-size: 160%;
    background-color: transparent;
  }
  </style>
  <% unless cloudinary_enabled? %>
  <script>
  (function() {
    var createStorageKey, host, uploadAttachment;

    document.addEventListener("trix-attachment-add", function(event) {
      var attachment;
      attachment = event.attachment;
      if (attachment.file) {
        return uploadAttachment(attachment);
      }
    });
    document.addEventListener('trix-attachment-remove', function(event) {
      var attachment;
      attachment = event.attachment;
      return deleteFile(attachment);
    });

    host = "<%= admin_images_path(format: :json) %>";

    uploadAttachment = function(attachment) {
      var file, form, key, xhr;
      file = attachment.file;
      key = createStorageKey(file);
      form = new FormData;
      form.append("key", key);
      form.append("Content-Type", file.type);
      form.append("image[file]", file);
      xhr = new XMLHttpRequest;
      xhr.responseType = 'json';
      xhr.open("POST", host, true);
      xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
      xhr.upload.onprogress = function(event) {
        var progress;
        progress = event.loaded / event.total * 100;
        return attachment.setUploadProgress(progress);
      };
      xhr.onload = function() {
        var href, url;
        if (xhr.status === 200) {
          return attachment.setAttributes({
            url: xhr.response.url,
            href: xhr.response.url,
            image_id: xhr.response.image_id
          });
        }
      };
      return xhr.send(form);
    };

    deleteFile = function(n) {
      return $.ajax({
        type: 'DELETE',
        url: '/admin/images/' + n.attachment.attributes.values.image_id,
        cache: false,
        contentType: false,
        processData: false
      });
    };

    createStorageKey = function(file) {
      var date, day, time;
      date = new Date();
      day = date.toISOString().slice(0, 10);
      time = date.getTime();
      return "tmp/" + day + "/" + time + "-" + file.name;
    };

  }).call(this);
  </script>
  <% end %>

  <%= f.input :title, label: I18n.translate("activerecord.attributes.doc.title", locale: I18n.locale), value: @doc.read_translated_attribute(:title) %>
  <% if params[:lang] == "#{I18n.locale}" %>
    <%= f.input("category_id", collection: Category.all.collect {|c| [ c.name, c.id ] }, prompt: t(:select_category, default: 'Select Category'), label: I18n.translate("activerecord.attributes.doc.category_id", locale: I18n.locale), :input_html => { class: 'no-translate' })  %>
  <% else %>
    <%= f.hidden_field("category_id", value: @doc.category_id) %>
  <% end %>
  <%= f.trix_editor :body, value: @doc.read_translated_attribute(:body) %>
  <% unless params[:lang] == "#{I18n.locale}" || @doc.translations.where(locale: locale).count > 0 %>
  <script>
    $('trix-editor').find('div').html('')
  </script>
  <% end %>
  </body>
  <hr/>
  <% if cloudinary_enabled? %>
    <div class="doc-form-files">
      <h4 class="form-subhead"><%= t('upload_image') %>:</h4>
      <%= cl_image_upload_tag(:image_id) %>
    </div>
  <% end %>
  <hr/>
  <h4 class="form-subhead"><%= t('additional_settings', default: 'Additional Settings') %>:</h4>
  <div class= "form_group no-translate">
    <label class="control-label" for="tag_list"><%= t('tags', default: 'Tags') %>: </label>
    <%= f.text_field :tag_list, value: @doc.tag_list.to_s, class: 'selectize form-control' %>
  </div>

  <%= f.input :meta_description, label: I18n.translate("activerecord.attributes.doc.meta_description", locale: I18n.locale), value: @doc.read_translated_attribute(:meta_description)  %>
  <%= f.input :title_tag, label: I18n.translate("activerecord.attributes.doc.title_tag", locale: I18n.locale), value: @doc.read_translated_attribute(:title_tag)  %>
  <%= f.input :keywords, label: I18n.translate("activerecord.attributes.doc.keywords", locale: I18n.locale), value: @doc.read_translated_attribute(:keywords)  %>

  <%#= f.text_field :rank %>
  <%= f.input(:front_page, class:'no-translate', inline: true, :label => I18n.translate("activerecord.attributes.doc.front_page", locale: I18n.locale, default: "Feature on front page?")) if params[:lang] == "#{I18n.locale}"  %>
  <%= f.input(:allow_comments, class:'no-translate', inline: true, :label => I18n.translate("activerecord.attributes.doc.allow_comments", locale: I18n.locale, default: "Allow Commenting")) if forums? and params[:lang] == "#{I18n.locale}"  %>
  <hr/>
  <% if params[:lang] == "#{I18n.locale}" %>
    <div class= "form_group no-translate">
      <label class="control-label" for="doc_active"><%= t('status', default: 'Article Status') %>: </label>
      <%= f.collection_radio_buttons :active, [[true, t('published_content', default: "Published")] ,[false, t('draft_content', default: "Draft")]], :first, :last %>
    </div>
  <% end %>
  <%= hidden_field_tag :lang, params[:lang] unless params[:lang].nil? %>
  <%= hidden_field_tag :obj_id, '' %>
  <br/><br/>
  <%= f.submit t('save_changes', default: "Save Changes"), class: 'btn btn-warning' %>
  <script type="text/javascript">
    $('.selectize').selectize({
      delimiter: ',',
      persist: false,
      create: function(input) {
          return {
              value: input,
              text: input
              }
          },
      // onItemAdd: function(value, $item) {
      //   char = $item.text().charAt(0);
      //   alert(char);
      //   //$item.parent().removeClass('selectize-input');
      //   $item.addClass('label');
      //   $item.addClass('label-doc-tagging');
      //   $item.addClass('label-' + char);
      // }
    });
  </script>

app/views/admin/docs/destroy.js.erb
$('#doc-#{@doc.id}').fadeOut();
Helpy.ready();
Helpy.track();

app/views/admin/docs/edit.html.erb
<% title "#{admin_title} #{t(:edit, default:'Edit')}: #{@doc.title}" %>

<h2 class="form-subhead"><%= t(:edit, default:'Edit') %>: <%= @doc.title %></h2>
<%= locale_select if AppSettings['i18n.available_locales'].count > 1 %>

<%= simple_form_for @doc, validate: true, url: admin_category_doc_path(category_id: @category.id, id: @doc.id), html: { method: :patch, id: :edit_doc } do |f| %>
  <% Globalize.with_locale(params['lang']) do %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= render :partial => 'form', :object => @doc, :locals => {:f => f} %>
  <% end %>
<% end %>
<% unless params[:lang].nil? %>
<script>
//$(function(){
//  $('.no-translate').attr("disabled", true);
//});
</script>
<% end %>

app/views/admin/docs/new.html.erb
<% title "#{admin_title} #{t(:new_content, default: 'New Content')}" %>

<div class="row">
  <%= simple_form_for([:admin, @doc], validate: true, multipart: true ) do |f| %>
  <div class="col-md-12">
    <h2 class="form-subhead"><%= t(:new_content, default: 'New Content') %></h2>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render :partial => 'form', :object => @doc, :locals => {:f => f} %>
  </div>
  <% end %>
</div>

<script>
var element = document.querySelector("trix-editor");
element.editor.setSelectedRange([0, 0]);
<% if @post.nil? %>
element.editor.insertHTML('<%= @doc.body if @doc.body? %>');
<% else %>
element.editor.insertHTML('<%= @post.body unless @post.nil? %>');
<% end %>
</script>