config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks, :invitations], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'notifications' => 'settings#notifications', as: :notifications
    put 'update_notifications' => 'settings#update_notifications', as: :update_notifications

    # Onboarding Routes
    get '/onboarding/index' => 'onboarding#index', as: :onboarding
    patch '/onboarding/update_user' => 'onboarding#update_user', as: :onboard_user
    patch '/onboarding/update_settings' => 'onboarding#update_settings', as: :onboard_settings
    get '/onboarding/complete' => 'onboarding#complete', as: :complete_onboard

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    resources :categories do
      resources :docs, except: [:index, :show]
    end
    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    resources :api_keys, except: [:show, :edit, :update]
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/team' => 'dashboard#stats', as: :stats
    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/entity/search.rb
module Entity
  class Search < Base
    expose :id
    expose :content
    expose :searchable_id
    expose :searchable_type
    expose :created_at
    expose :updated_at
  end
end

app/controllers/admin/search_controller.rb
class Admin::SearchController < Admin::BaseController

  before_action :verify_agent
  before_action :fetch_counts
  before_action :remote_search
  before_action :get_all_teams
  before_action :search_date_from_params

  respond_to :html, :js

  # simple search tickets by # and user
  def topic_search

    # search for user, if [one] found, we'll give details on that person
    # if more than one found, we'll list them, if search is for "users" then show all
    if params[:q] == 'users'
      users = User.all
    else
      users = User.user_search(params[:q])
    end

    if users.size == 0 # not a user search, so look for topics
      search_topics
      template = 'admin/search/search'
      tracker("Admin Search", "Topic Search", params[:q])
    elsif users.size == 1
      @user = users.first
      @topics = Topic.where(user_id: @user.id).page params[:page]
      @topic = Topic.where(user_id: @user.id).first unless @user.nil?
      template = 'admin/users/show'
      tracker("Admin Search", "User Search", params[:q])
      tracker("Agent: #{current_user.name}", "Viewed User Profile", @user.name)
    else
      @users = users.page params[:page]
      template = 'admin/users/users'
      tracker("Admin Search", "User Search", params[:q])
    end

    render template
  end

  protected

  def search_topics
    topics_to_search = Topic.where('created_at >= ?', @start_date).where('created_at <= ?', @end_date)
    if current_user.is_restricted? && teams?
      @topics = topics_to_search.admin_search(params[:q]).tagged_with(current_user.team_list, :any => true).page params[:page]
    else
      @topics = topics_to_search.admin_search(params[:q]).page params[:page]
    end
  end

  def search_date_from_params
    if params[:start_date].present?
      @start_date = params[:start_date].to_datetime
    else
      @start_date = Time.zone.today-1.month
    end

    if params[:end_date].present?
      @end_date = params[:end_date].to_datetime
    else
      @end_date = Time.zone.today.at_end_of_day
    end
  end


end

app/controllers/api/v1/search.rb
module API
  module V1
    class Search < Grape::API

      before do
        authenticate!
      end

      include API::V1::Defaults
      resource :search, desc: "Search the KB or community discussions" do

        # throttle max: 200, per: 1.minute

        ## SEARCH PUBLIC KNOWLEDGEBASE
        desc "Search the knowledgebase", {
          notes: "Search for docs, posts, and topics by query"
        }
        params do
          requires :q, type: String, desc: "The query term to search for"
          optional :type, type: String, desc: "The type of entity to search for"
          optional :page, type: Integer, desc: "The current page", default: 1
          optional :per_page, type: Integer, desc: "The number of results to return per page", default: 25
        end
        get "", root: :search do

          # Build initial results of the search
          results = PgSearch.multisearch(permitted_params[:q])
                            .page(permitted_params[:page])
                            .per(permitted_params[:per_page])

          # Scope results to supplied type
          if permitted_params[:type].present?
            # Convert pluralized into singular for the searcher
            type = permitted_params[:type].singularize.camelize
            results = results.where(searchable_type: type)
                             .includes(:searchable)
          end

          # Grab total pagesnow in case we have to map the results array
          total_pages = results.total_pages


          # Check what kind of entity we are searching for and modify the Entity output accordingly
          entity = case type
                   when nil
                     Entity::Search
                   when 'Doc', 'Topic', 'User'
                     results = results.map(&:searchable)
                     "Entity::#{type}".constantize
                   end

          present pages: {
            page: permitted_params[:page],
            per_page: permitted_params[:per_page],
            total_pages: total_pages
          }
          present :results, results, with: entity, category: true
        end
      end
    end
  end
end

app/views/admin/search/_topic_search.html.erb
<%= form_tag admin_topic_search_path, method: :get, remote: true, class: 'admin-search submit-loader form-inline form-horizontal', id: 'search-form' do %>
  <div class="form-group">
    <div class="col-xs-12 col-sm-7 col-md-7">
      <%= text_field_tag('q', nil, placeholder: t(:search, default: 'Search'), value: params[:q], class: 'form-control search-field', style: "width: 100%;" )%>
    </div>
    <div class="col-sm-2 col-md-2 hidden-xs text-center">
      <div class="input-group date">
        <%= text_field_tag :start_date, nil, class: 'form-control' %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
      </div>
    </div>
    <div class="col-sm-2 col-md-2 hidden-xs text-center">
      <div class="input-group date">
        <%= text_field_tag :end_date, nil, class: 'form-control' %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
      </div>
    </div>
    <div class="submit-group col-sm-1 col-md-1 text-right">
      <%= submit_tag t('search', default: 'Search'), class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/search/search.js.erb
$('#tickets').html("<%= escape_javascript(render 'admin/topics/tickets') %>");
$('.ticket-stats').html("<%= j render 'admin/topics/ticket_stats' %>");
$('#user-info').html("<%= j render 'admin/users/user_info_horizontal' if @user %>");
$('#ticket-page-title').show().html("<%= t(:results_found, count: number_to_human(@topics.total_count)) %> <span class='more-important'>\"<%= params[:q] %>\"</span> <span class='label <%= status_class(@status) %>' style='text-transform: uppercase'><%= status_label(@status) if @status %></span> <span class='hidden-xs pull-right'><%= j link_to t(:open_new_discussion, default: 'Open Discussion'), new_admin_topic_path, remote: true, class: 'btn btn-primary' %></span><%= escape_javascript(render 'admin/topics/ticket_nav_dropdown') %>");
$(document).prop('title', "<%= admin_title %> <%= t(:results_found, count:  number_to_human(@topics.total_count)) %>: <%= @status.titleize if @status %>");
history.pushState(null, null, '<%= admin_topic_search_path(q: params[:q], start_date: params[:start_date], end_date: params[:end_date]).html_safe %>');

// Empty ticket search field and show
// $('#q').val('');
$('.topic-search').show();

// Update timestamps
$('.last-active time[data-time-ago]').timeago();

// Send ping to GA
ga('send', 'pageview');

// jQuery hook
Helpy.ready();
Helpy.track();
Helpy.logHistory();

// RTL changes?
<%= "Helpy.rtl();" if rtl? %>